import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  // Tagines
  {
    id: 'tagine_fish',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Fish Tagine', ar: 'طاجين السمك' },
    description: { en: 'Traditional Moroccan fish tagine with vegetables and spices.', ar: 'طاجين السمك المغربي التقليدي مع الخضار والتوابل.' },
    price: 60,
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_chicken',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Chicken Tagine', ar: 'طاجين الدجاج' },
    description: { en: 'Classic chicken tagine with preserved lemons and olives.', ar: 'طاجين الدجاج الكلاسيكي بالليمون المصير والزيتون.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_meat',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Meat Tagine', ar: 'طاجين اللحم' },
    description: { en: 'Rich meat tagine cooked slowly with spices.', ar: 'طاجين لحم غني مطهو ببطء مع التوابل.' },
    price: 70,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
  },
  // Grilled
  {
    id: 'grilled_sardines',
    category: { en: 'Grilled', ar: 'مشاوي' },
    name: { en: 'Grilled Sardines', ar: 'سردين مشوي' },
    description: { en: 'Freshly grilled sardines with herbs and lemon.', ar: 'سردين مشوي طازج مع الأعشاب والليمون.' },
    price: 30,
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'grilled_turkey',
    category: { en: 'Grilled', ar: 'مشاوي' },
    name: { en: 'Grilled Turkey (La Dande)', ar: 'لاداند مشوي' },
    description: { en: 'Tender grilled turkey skewers.', ar: 'أسياخ الديك الرومي المشوية الطرية.' },
    price: 40,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'grilled_chicken',
    category: { en: 'Grilled', ar: 'مشاوي' },
    name: { en: 'Grilled Chicken', ar: 'دجاج مشوي' },
    description: { en: 'Charcoal grilled chicken half with sides.', ar: 'نصف دجاجة مشوية على الفحم مع مقبلات.' },
    price: 45,
    image: 'https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?auto=format&fit=crop&w=600&q=80',
  },
  // Tea & Coffee
  {
    id: 'tea_mint',
    category: { en: 'Tea & Coffee', ar: 'أتاي و قهوة' },
    name: { en: 'Mint Tea', ar: 'أتاي بالنعناع' },
    description: { en: 'Traditional Moroccan mint tea.', ar: 'شاي مغربي أصيل بالنعناع.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1576092762791-dd9e222064af?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tea_louisa',
    category: { en: 'Tea & Coffee', ar: 'أتاي و قهوة' },
    name: { en: 'Verbena Tea (Louisa)', ar: 'أتاي باللويزة' },
    description: { en: 'Soothing tea with fresh lemon verbena.', ar: 'شاي مهدئ باللويزة الطازجة.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'coffee_nescafe',
    category: { en: 'Tea & Coffee', ar: 'أتاي و قهوة' },
    name: { en: 'Nescafe', ar: 'نسكافيه' },
    description: { en: 'Classic instant coffee.', ar: 'قهوة سريعة التحضير.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1572097662444-003d63af5c4c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'coffee_black',
    category: { en: 'Tea & Coffee', ar: 'أتاي و قهوة' },
    name: { en: 'Coffee', ar: 'قهوة' },
    description: { en: 'Freshly brewed black coffee or espresso.', ar: 'قهوة سوداء أو إسبريسو.' },
    price: 12,
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80',
  },
  // Sodas
  {
    id: 'soda_sprite',
    category: { en: 'Sodas', ar: 'مشروبات غازية' },
    name: { en: 'Sprite', ar: 'سبرايت' },
    description: { en: 'Refreshing lemon-lime soda.', ar: 'مشروب غازي منعش بنكهة الليمون.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_poms',
    category: { en: 'Sodas', ar: 'مشروبات غازية' },
    name: { en: 'Poms', ar: 'بومس' },
    description: { en: 'Apple flavored soda.', ar: 'مشروب غازي بنكهة التفاح.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_hawai',
    category: { en: 'Sodas', ar: 'مشروبات غازية' },
    name: { en: 'Hawai', ar: 'هاواي' },
    description: { en: 'Tropical flavored soda.', ar: 'مشروب غازي بنكهة الفواكه الاستوائية.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1605615822998-35649f8eb738?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_fanta',
    category: { en: 'Sodas', ar: 'مشروبات غازية' },
    name: { en: 'Fanta', ar: 'فانتا' },
    description: { en: 'Orange flavored soda.', ar: 'مشروب غازي بنكهة البرتقال.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_coca',
    category: { en: 'Sodas', ar: 'مشروبات غازية' },
    name: { en: 'Coca Cola', ar: 'كوكا كولا' },
    description: { en: 'Classic cola soda.', ar: 'مشروب كولا غازي.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  // Energy Drinks
  {
    id: 'energy_linx',
    category: { en: 'Energy Drinks', ar: 'مشروبات طاقة' },
    name: { en: 'Linx', ar: 'لينكس' },
    description: { en: 'Energy drink.', ar: 'مشروب طاقة.' },
    price: 20,
    image: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'energy_mg',
    category: { en: 'Energy Drinks', ar: 'مشروبات طاقة' },
    name: { en: 'Mg', ar: 'إم جي' },
    description: { en: 'Energy drink.', ar: 'مشروب طاقة.' },
    price: 20,
    image: 'https://images.unsplash.com/photo-1594971475674-6a97f8aff7ae?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'energy_redbull',
    category: { en: 'Energy Drinks', ar: 'مشروبات طاقة' },
    name: { en: 'Redbull', ar: 'ريد بول' },
    description: { en: 'Energy drink that gives you wings.', ar: 'مشروب طاقة.' },
    price: 25,
    image: 'https://images.unsplash.com/photo-1616053816738-4e19af33eb32?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'energy_donsimon',
    category: { en: 'Energy Drinks', ar: 'مشروبات طاقة' },
    name: { en: 'Don Simon', ar: 'دون سيمون' },
    description: { en: 'Juice drink.', ar: 'مشروب عصير.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=600&q=80',
  }
];

export const translations = {
  en: {
    menu: 'Menu',
    cart: 'Your Order',
    emptyCart: 'Your cart is empty',
    total: 'Total',
    tableNumber: 'Table Number',
    sendOrder: 'Send Order',
    currency: 'MAD',
    addToCart: 'Add',
    tableRequired: 'Please enter your table number.',
    languageToggle: 'العربية',
    restaurantName: 'DAR ALBAHR',
    restaurantSubname: 'Seafood',
    slogan: 'Fresh from the port, cooked to order',
    editMenu: 'Edit Menu',
    doneEditing: 'Done',
    all: 'All',
  },
  ar: {
    menu: 'القائمة',
    cart: 'طلبك',
    emptyCart: 'عربة التسوق فارغة',
    total: 'المجموع',
    tableNumber: 'رقم الطاولة',
    sendOrder: 'إرسال الطلب',
    currency: 'د.م.',
    addToCart: 'إضافة',
    tableRequired: 'يرجى إدخال رقم الطاولة.',
    languageToggle: 'English',
    restaurantName: 'دار البحر',
    restaurantSubname: 'مأكولات بحرية',
    slogan: 'طازج من الميناء، يُطهى عند الطلب',
    editMenu: 'تعديل القائمة',
    doneEditing: 'تم',
    all: 'الكل',
  }
};
