import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'friture_500',
    category: { en: 'Fish & Seafood', ar: 'الأسماك', fr: 'Poissons et Fruits de Mer', es: 'Pescados y Mariscos' },
    name: { en: 'Mixed Fried Fish (500g)', ar: 'تشكيلة سمك مقلي 500 غرام', fr: 'Friture de Poisson (500g)', es: 'Fritura de Pescado (500g)' },
    description: { en: 'A 500g mix of fresh fried fish.', ar: 'نصف كيلو سمك مقلي منوع (شطون، ميرنا، بكالاو، بنوها، كروفيت).', fr: '500g de friture de poisson frais assorti.', es: '500g de fritura de pescado fresco variado.' },
    price: 60,
    image: 'https://images.unsplash.com/photo-1599084990807-81c0bf302521?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_1kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك', fr: 'Poissons et Fruits de Mer', es: 'Pescados y Mariscos' },
    name: { en: 'Mixed Fried Fish (1kg)', ar: 'تشكيلة سمك مقلي 1 كيلو', fr: 'Friture de Poisson (1kg)', es: 'Fritura de Pescado (1kg)' },
    description: { en: 'A 1kg mix of fresh fried fish for 2 people.', ar: 'كيلو سمك مقلي منوع لفردين.', fr: '1kg de friture de poisson frais pour 2 personnes.', es: '1kg de fritura de pescado fresco para 2 personas.' },
    price: 120,
    image: 'https://images.unsplash.com/photo-1599084990807-81c0bf302521?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_500',
    category: { en: 'Fish & Seafood', ar: 'الأسماك', fr: 'Poissons et Fruits de Mer', es: 'Pescados y Mariscos' },
    name: { en: 'Fish Friture (500g)', ar: 'فريتورا الحوت 500 غرام', fr: 'Friture de Poisson Simple (500g)', es: 'Fritura de Pescado Simple (500g)' },
    description: { en: 'Fresh fish friture for 1 person.', ar: 'فريتورا الحوت الطازجة لفرد واحد.', fr: 'Friture de poisson frais pour 1 personne.', es: 'Fritura de pescado fresco para 1 persona.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_1kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك', fr: 'Poissons et Fruits de Mer', es: 'Pescados y Mariscos' },
    name: { en: 'Fish Friture (1kg)', ar: 'فريتورا الحوت 1 كيلو', fr: 'Friture de Poisson Simple (1kg)', es: 'Fritura de Pescado Simple (1kg)' },
    description: { en: 'Fresh fish friture for 2 people.', ar: 'فريتورا الحوت الطازجة لفردين.', fr: 'Friture de poisson frais pour 2 personnes.', es: 'Fritura de pescado fresco para 2 personas.' },
    price: 100,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_1.5kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك', fr: 'Poissons et Fruits de Mer', es: 'Pescados y Mariscos' },
    name: { en: 'Fish Friture (1.5kg)', ar: 'فريتورا الحوت 1.5 كيلو', fr: 'Friture de Poisson Simple (1.5kg)', es: 'Fritura de Pescado Simple (1.5kg)' },
    description: { en: 'Fresh fish friture for 3 people.', ar: 'فريتورا الحوت الطازجة لـ 3 أفراد.', fr: 'Friture de poisson frais pour 3 personnes.', es: 'Fritura de pescado fresco para 3 personas.' },
    price: 150,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'grilled_sardines',
    category: { en: 'Grilled', ar: 'مشاوي', fr: 'Grillades', es: 'Parrilladas' },
    name: { en: 'Grilled Sardines', ar: 'سردين مشوي', fr: 'Sardines Grillées', es: 'Sardinas a la Plancha' },
    description: { en: 'Freshly grilled sardines.', ar: 'سردين مشوي طازج.', fr: 'Sardines fraîchement grillées.', es: 'Sardinas frescas a la plancha.' },
    price: 30,
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_fish',
    category: { en: 'Tagines', ar: 'طواجن', fr: 'Tajines', es: 'Tayines' },
    name: { en: 'Fish Tagine', ar: 'طاجين الحوت', fr: 'Tajine de Poisson', es: 'Tayín de Pescado' },
    description: { en: 'Traditional Moroccan fish tagine.', ar: 'طاجين الحوت المغربي التقليدي.', fr: 'Tajine de poisson marocain traditionnel.', es: 'Tayín tradicional marroquí de pescado.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_meat',
    category: { en: 'Tagines', ar: 'طواجن', fr: 'Tajines', es: 'Tayines' },
    name: { en: 'Meat Tagine', ar: 'طاجين اللحم', fr: 'Tajine de Viande', es: 'Tayín de Carne' },
    description: { en: 'Rich meat tagine.', ar: 'طاجين لحم غني.', fr: 'Riche tajine de viande.', es: 'Rico tayín de carne.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_chicken',
    category: { en: 'Tagines', ar: 'طواجن', fr: 'Tajines', es: 'Tayines' },
    name: { en: 'Chicken Tagine', ar: 'طاجين الدجاج', fr: 'Tajine de Poulet', es: 'Tayín de Pollo' },
    description: { en: 'Classic chicken tagine.', ar: 'طاجين الدجاج الكلاسيكي.', fr: 'Tajine de poulet classique.', es: 'Tayín de pollo clásico.' },
    price: 40,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sauce',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية', fr: 'Entrées et Accompagnements', es: 'Entrantes y Guarniciones' },
    name: { en: 'Sauce', ar: 'لاصوص', fr: 'Sauce', es: 'Salsa' },
    description: { en: 'Sauce.', ar: 'صلصة.', fr: 'Sauce.', es: 'Salsa.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772dc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bissara',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية', fr: 'Entrées et Accompagnements', es: 'Entrantes y Guarniciones' },
    name: { en: 'Bissara', ar: 'بيصارة', fr: 'Bissara', es: 'Bissara' },
    description: { en: 'Fava bean soup.', ar: 'حساء البيصارة اللذيذ.', fr: 'Soupe aux fèves.', es: 'Sopa de habas.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'rice_paella',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية', fr: 'Entrées et Accompagnements', es: 'Entrantes y Guarniciones' },
    name: { en: 'Rice Paella', ar: 'روز باييلا', fr: 'Riz Paella', es: 'Arroz Paella' },
    description: { en: 'Delicious rice paella.', ar: 'أرز باييلا شهي.', fr: 'Délicieux riz paella.', es: 'Delicioso arroz paella.' },
    price: 20,
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'fries',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية', fr: 'Entrées et Accompagnements', es: 'Entrantes y Guarniciones' },
    name: { en: 'Fries', ar: 'فريت', fr: 'Frites', es: 'Patatas Fritas' },
    description: { en: 'Crispy french fries.', ar: 'بطاطس مقلية مقرمشة.', fr: 'Frites croustillantes.', es: 'Patatas fritas crujientes.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'salad',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية', fr: 'Entrées et Accompagnements', es: 'Entrantes y Guarniciones' },
    name: { en: 'Salad', ar: 'شلاضة', fr: 'Salade', es: 'Ensalada' },
    description: { en: 'Fresh mixed salad.', ar: 'سلطة مشكلة طازجة.', fr: 'Salade mixte fraîche.', es: 'Ensalada mixta fresca.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tea',
    category: { en: 'Drinks', ar: 'مشروبات', fr: 'Boissons', es: 'Bebidas' },
    name: { en: 'Tea', ar: 'أتاي', fr: 'Thé', es: 'Té' },
    description: { en: 'Moroccan mint tea.', ar: 'شاي مغربي أصيل.', fr: 'Thé à la menthe marocain.', es: 'Té de menta marroquí.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1576092762791-dd9e222064af?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_half_liter',
    category: { en: 'Drinks', ar: 'مشروبات', fr: 'Boissons', es: 'Bebidas' },
    name: { en: 'Soda (0.5L)', ar: 'مونادا نص ليتر', fr: 'Soda (0.5L)', es: 'Refresco (0.5L)' },
    description: { en: '0.5 liter soda.', ar: 'مشروب غازي نصف لتر.', fr: 'Soda de 0,5 litre.', es: 'Refresco de 0,5 litros.' },
    price: 8,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'water_small',
    category: { en: 'Drinks', ar: 'مشروبات', fr: 'Boissons', es: 'Bebidas' },
    name: { en: 'Small Water', ar: 'ماء صغير', fr: 'Petite Eau', es: 'Agua Pequeña' },
    description: { en: 'Small bottle of water.', ar: 'قنينة ماء صغيرة.', fr: 'Petite bouteille d eau.', es: 'Botella pequeña de agua.' },
    price: 5,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'water_large',
    category: { en: 'Drinks', ar: 'مشروبات', fr: 'Boissons', es: 'Bebidas' },
    name: { en: 'Large Water', ar: 'ماء كبير', fr: 'Grande Eau', es: 'Agua Grande' },
    description: { en: 'Large bottle of water.', ar: 'قنينة ماء كبيرة.', fr: 'Grande bouteille d eau.', es: 'Botella grande de agua.' },
    price: 8,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4c?auto=format&fit=crop&w=600&q=80',
  }
];

export const translations = {
  en: {
    menu: 'Menu',
    cart: 'Your Order',
    emptyCart: 'Your cart is empty',
    total: 'Total',
    tableNumber: 'Table Number',
    sendOrder: 'Send Order',
    currency: 'MAD',
    addToCart: 'Add',
    tableRequired: 'Please enter your table number.',
    languageToggle: 'العربية',
    restaurantName: 'DAR ALBAHR',
    restaurantSubname: 'Seafood',
    slogan: 'Fresh from the port, cooked to order',
    editMenu: 'Edit Menu',
    doneEditing: 'Done',
    all: 'All',
    orderSuccess: 'Your order has been sent successfully!',
    newOrderPlaceholder: 'Enter table number here...'
  },
  ar: {
    menu: 'القائمة',
    cart: 'طلبك',
    emptyCart: 'عربة التسوق فارغة',
    total: 'المجموع',
    tableNumber: 'رقم الطاولة',
    sendOrder: 'إرسال الطلب',
    currency: 'د.م.',
    addToCart: 'إضافة',
    tableRequired: 'يرجى إدخال رقم الطاولة.',
    languageToggle: 'English',
    restaurantName: 'دار البحر',
    restaurantSubname: 'مأكولات بحرية',
    slogan: 'طازج من الميناء، يُطهى عند الطلب',
    editMenu: 'تعديل القائمة',
    doneEditing: 'تم',
    all: 'الكل',
    orderSuccess: 'لقد تم إرسال طلبك بنجاح!',
    newOrderPlaceholder: 'أدخل رقم الطاولة هنا...'
  },
  fr: {
    menu: 'Menu',
    cart: 'Votre Commande',
    emptyCart: 'Votre panier est vide',
    total: 'Total',
    tableNumber: 'Numéro de Table',
    sendOrder: 'Envoyer',
    currency: 'MAD',
    addToCart: 'Ajouter',
    tableRequired: 'Veuillez entrer votre numéro de table.',
    languageToggle: 'English',
    restaurantName: 'DAR ALBAHR',
    restaurantSubname: 'Fruits de Mer',
    slogan: 'Frais du port, cuisiné à la commande',
    editMenu: 'Modifier Menu',
    doneEditing: 'Terminé',
    all: 'Tout',
    orderSuccess: 'Votre commande a été envoyée avec succès !',
    newOrderPlaceholder: 'Entrez le numéro de table ici...'
  },
  es: {
    menu: 'Menú',
    cart: 'Tu Pedido',
    emptyCart: 'Tu carrito está vacío',
    total: 'Total',
    tableNumber: 'Número de Mesa',
    sendOrder: 'Enviar',
    currency: 'MAD',
    addToCart: 'Añadir',
    tableRequired: 'Por favor, introduzca su número de mesa.',
    languageToggle: 'English',
    restaurantName: 'DAR ALBAHR',
    restaurantSubname: 'Mariscos',
    slogan: 'Fresco del puerto, cocinado a pedido',
    editMenu: 'Editar Menú',
    doneEditing: 'Hecho',
    all: 'Todo',
    orderSuccess: '¡Su pedido ha sido enviado con éxito!',
    newOrderPlaceholder: 'Ingrese el número de mesa aquí...'
  }
};
