import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  // Fish & Seafood
  {
    id: 'friture_500',
    category: { en: 'Fish & Seafood', ar: 'الأسماك' },
    name: { en: 'Mixed Fried Fish (500g)', ar: 'تشكيلة سمك مقلي 500 غرام' },
    description: { en: 'A 500g mix of fresh fried fish.', ar: 'نصف كيلو سمك مقلي منوع (شطون، ميرنا، بكالاو، بنوها، كروفيت).' },
    price: 60,
    image: 'https://images.unsplash.com/photo-1599084990807-81c0bf302521?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_1kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك' },
    name: { en: 'Mixed Fried Fish (1kg)', ar: 'تشكيلة سمك مقلي 1 كيلو' },
    description: { en: 'A 1kg mix of fresh fried fish for 2 people.', ar: 'كيلو سمك مقلي منوع لفردين.' },
    price: 120,
    image: 'https://images.unsplash.com/photo-1599084990807-81c0bf302521?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_500',
    category: { en: 'Fish & Seafood', ar: 'الأسماك' },
    name: { en: 'Fish Friture (500g)', ar: 'فريتورا الحوت 500 غرام' },
    description: { en: 'Fresh fish friture for 1 person.', ar: 'فريتورا الحوت الطازجة لفرد واحد.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_1kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك' },
    name: { en: 'Fish Friture (1kg)', ar: 'فريتورا الحوت 1 كيلو' },
    description: { en: 'Fresh fish friture for 2 people.', ar: 'فريتورا الحوت الطازجة لفردين.' },
    price: 100,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'friture_basic_1.5kg',
    category: { en: 'Fish & Seafood', ar: 'الأسماك' },
    name: { en: 'Fish Friture (1.5kg)', ar: 'فريتورا الحوت 1.5 كيلو' },
    description: { en: 'Fresh fish friture for 3 people.', ar: 'فريتورا الحوت الطازجة لـ 3 أفراد.' },
    price: 150,
    image: 'https://images.unsplash.com/photo-1588796538421-e0c96fb5f522?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'grilled_sardines',
    category: { en: 'Grilled', ar: 'مشاوي' },
    name: { en: 'Grilled Sardines', ar: 'سردين مشوي' },
    description: { en: 'Freshly grilled sardines.', ar: 'سردين مشوي طازج.' },
    price: 30,
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=600&q=80',
  },
  // Tagines
  {
    id: 'tagine_fish',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Fish Tagine', ar: 'طاجين الحوت' },
    description: { en: 'Traditional Moroccan fish tagine.', ar: 'طاجين الحوت المغربي التقليدي.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_meat',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Meat Tagine', ar: 'طاجين اللحم' },
    description: { en: 'Rich meat tagine.', ar: 'طاجين لحم غني.' },
    price: 50,
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'tagine_chicken',
    category: { en: 'Tagines', ar: 'طواجن' },
    name: { en: 'Chicken Tagine', ar: 'طاجين الدجاج' },
    description: { en: 'Classic chicken tagine.', ar: 'طاجين الدجاج الكلاسيكي.' },
    price: 40,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
  },
  // Starters & Sides
  {
    id: 'sauce',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية' },
    name: { en: 'Sauce', ar: 'لاصوص' },
    description: { en: 'Sauce.', ar: 'صلصة.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772dc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bissara',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية' },
    name: { en: 'Bissara', ar: 'بيصارة' },
    description: { en: 'Fava bean soup.', ar: 'حساء البيصارة اللذيذ.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'rice_paella',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية' },
    name: { en: 'Rice Paella', ar: 'روز باييلا' },
    description: { en: 'Delicious rice paella.', ar: 'أرز باييلا شهي.' },
    price: 20,
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'fries',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية' },
    name: { en: 'Fries', ar: 'فريت' },
    description: { en: 'Crispy french fries.', ar: 'بطاطس مقلية مقرمشة.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'salad',
    category: { en: 'Starters & Sides', ar: 'مقبلات و أطباق جانبية' },
    name: { en: 'Salad', ar: 'شلاضة' },
    description: { en: 'Fresh mixed salad.', ar: 'سلطة مشكلة طازجة.' },
    price: 15,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
  },
  // Drinks
  {
    id: 'tea',
    category: { en: 'Drinks', ar: 'مشروبات' },
    name: { en: 'Tea', ar: 'أتاي' },
    description: { en: 'Moroccan mint tea.', ar: 'شاي مغربي أصيل.' },
    price: 10,
    image: 'https://images.unsplash.com/photo-1576092762791-dd9e222064af?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'soda_half_liter',
    category: { en: 'Drinks', ar: 'مشروبات' },
    name: { en: 'Soda (0.5L)', ar: 'مونادا نص ليتر' },
    description: { en: '0.5 liter soda.', ar: 'مشروب غازي نصف لتر.' },
    price: 8,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'water_small',
    category: { en: 'Drinks', ar: 'مشروبات' },
    name: { en: 'Small Water', ar: 'ماء صغير' },
    description: { en: 'Small bottle of water.', ar: 'قنينة ماء صغيرة.' },
    price: 5,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'water_large',
    category: { en: 'Drinks', ar: 'مشروبات' },
    name: { en: 'Large Water', ar: 'ماء كبير' },
    description: { en: 'Large bottle of water.', ar: 'قنينة ماء كبيرة.' },
    price: 8,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4c?auto=format&fit=crop&w=600&q=80',
  }
];

export const translations = {
  en: {
    menu: 'Menu',
    cart: 'Your Order',
    emptyCart: 'Your cart is empty',
    total: 'Total',
    tableNumber: 'Table Number',
    sendOrder: 'Send Order',
    currency: 'MAD',
    addToCart: 'Add',
    tableRequired: 'Please enter your table number.',
    languageToggle: 'العربية',
    restaurantName: 'DAR ALBAHR',
    restaurantSubname: 'Seafood',
    slogan: 'Fresh from the port, cooked to order',
    editMenu: 'Edit Menu',
    doneEditing: 'Done',
    all: 'All',
  },
  ar: {
    menu: 'القائمة',
    cart: 'طلبك',
    emptyCart: 'عربة التسوق فارغة',
    total: 'المجموع',
    tableNumber: 'رقم الطاولة',
    sendOrder: 'إرسال الطلب',
    currency: 'د.م.',
    addToCart: 'إضافة',
    tableRequired: 'يرجى إدخال رقم الطاولة.',
    languageToggle: 'English',
    restaurantName: 'دار البحر',
    restaurantSubname: 'مأكولات بحرية',
    slogan: 'طازج من الميناء، يُطهى عند الطلب',
    editMenu: 'تعديل القائمة',
    doneEditing: 'تم',
    all: 'الكل',
  }
};
